language: c

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit2.0
    - LUA=luajit2.1

before_install:
  - bash .travis/setup_lua.sh
  - sudo luarocks install luacov-coveralls
  - sudo luarocks install busted

script:
  - busted -c

after_success:
  - luacov-coveralls -v

notifications:
  email:
    on_success: change
    on_failure: always
